apiVersion: v1
kind: Namespace
metadata:
  name: testproj1-prod
  labels:
    environment-id: env_fbb03dff-91a3-4d87-bd95-bd95dc1dffd4
    project-id: project_0c2e5d6b-1fca-4141-83b6-e7fda72471d2
    project-name: testProj1
    environment-name: prod
    organization-id: org_49cd1834-c20d-41ad-9b93-076c8acb87ce
